/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

int main(void)
{
	printf("size of char=%u\n",sizeof(char));
	printf("size of of int =%u\n",sizeof(int));
	printf("size of of float=%u\n",sizeof(float));
	printf("size of of long=%u\n",sizeof(long));
	printf("size of of long long=%u\n",sizeof(long long));
	printf("size of of short=%u\n",sizeof(short));
    /* Loop forever */
	for(;;);
}
