/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Loop forever */
	uint32_t *pClk= (uint32_t *)(0x40023830);
	uint32_t *pPinmode=(uint32_t *)(0x40020400);
	uint32_t *pOpdata=(uint32_t *)(0x40020414);

	*pClk=*pClk|(0x00000002);
	*pPinmode=*pPinmode&(0xffff3fff);
	*pPinmode=*pPinmode|(0x00004000);
	*pOpdata=*pOpdata|(0x00000080);

	for(;;);
}
